language: java
sudo: required
script: mvn clean verify

services:
  - docker
  
after_success:
  - docker login -u joelcrisanto -p $DOCKER_PASSWORD
  - docker build --tag joelcrisanto/dspringboot .
  #- docker tag latest joelcrisanto/dspringboot
  - docker push joelcrisanto/dspringboot
