language: java
sudo: required

services:
  - docker
  
after_success:
  - docker login -u joelcrisanto -p $DOCKER_PASSWORD
  - docker build --tag joelcrisanto/dspringboot .
  #- docker tag latest joelcrisanto/dspringboot
  - docker push joelcrisanto/dspringboot
  
notifications:
  email:
    - yourname@gmail.com
